version: '2'
services:
  web:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  api:
    build: Docker/web
    command: bash -c "npm install; nodemon app.js"
    volumes:
      - ./app/:/usr/src/app

    environment:
      - VIRTUAL_HOST=localhost
